# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/Users/maksimbogdanovich/Desktop/Новая папка/API"
      dockerfile: "API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "/Users/maksimbogdanovich/Desktop/Новая папка/API/API:/app:rw"
    - "/Users/maksimbogdanovich/Desktop/Новая папка/API:/src:rw"
    - "/Users/maksimbogdanovich/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
